log_level = "debug"

[[proxy]]
[proxy.listener]
bind_address = "0.0.0.0:6433"
server_cert = "/app/certs/proxy.crt"
server_key = "/app/certs/proxy.key"
mtls = false

[proxy.backend]
address = "postgres-tls:5432"
tls_enabled = true
root_ca = "/app/certs/ca.crt"
